import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-mono`}
      >
        <div className="flex flex-col bg-foreground/10 min-h-screen px-3">
          <Navbar />
          <div
            className="bg-background rounded-[14px] overflow-auto"
            style={{ height: `calc(100dvh - 120px)` }}
          >
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
